### ISSUE TITLE
Pass Username and Password as oc publish command line arguments

### ISSUE THREAD

**Issue by navamgupta** [andyroyle/oc-auth-ldap#2]
Doing something like 

```
oc publish component -u xxx@xx.com -p xxxx
```

would make it super convenient dealing with build and deployment systems like Jenkins.
we dont have have to use -u and -p in particular we could pick for a variety of styles/names out there. 
I feel like this change might not be part of the oc-auth-ldap plugin but more part of the oc client and registry code. Let me know if you want me to create a ticket in the main oc project instead.

**Comment by matteofigus** [comment]
Hi @navamgupta this is already available

oc publish component --username username --password password

we also have --registry https://registryURL if you want to force the publish to happen to a specific url.

@andyroyle can I guess you can close this

**Comment by andyroyle** [comment]
@navamgupta we can discuss more on gitter if you need help
